# The HIVMC Version number information

if(NOT DEFINED HIVMC_VERSION_MAJOR)
    set(HIVMC_VERSION_MAJOR 0)
endif()
if(NOT DEFINED HIVMC_VERSION_MINOR)
    set(HIVMC_VERSION_MINOR 3)
endif()
if(NOT DEFINED HIVMC_VERSION_PATCH)
    set(HIVMC_VERSION_PATCH 0)
endif()
if(NOT DEFINED HIVMC_VERSION_SUFFIX)
    set(HIVMC_VERSION_SUFFIX)
endif()
