if(MLIR_INCLUDE_TESTS)
  set(TEST_LIBS
    BiShengIRTestDialect
    MLIRTestDialect
    MLIRTestTransformDialect
    MLIRTestTransforms
  )
endif()

set(LIBS
  ${TEST_LIBS}
  BiShengIRAnnotationDialect
  BiShengIRAnnotationTransforms
  BiShengIRAscendDPXDialect
  BiShengIRBufferizationTransforms
  BiShengIRDialectUtils
  BiShengIRExecutionEngineTransforms
  BiShengIRFuncToLLVM
  BiShengIRHACCDialect
  BiShengIRHACCPipelines
  BiShengIRHACCTransforms
  BiShengIRHACCUtils
  BiShengIRHFusionDialect
  BiShengIRHFusionTransformOps
  BiShengIRHFusionTransforms
  BiShengIRHFusionUtils
  BiShengIRHIVMCLib
  BiShengIRHIVMDialect
  BiShengIRHIVMTransformOps
  BiShengIRHIVMTransforms
  BiShengIRLLVMCommonConversion
  BiShengIRLinalgCanonicalizations
  BiShengIRLinalgDialectExt
  BiShengIRMathExtDialect
  BiShengIRMemRefDialect
  BiShengIRMemRefExtDialect
  BiShengIRPass
  BiShengIRRetriablePassManager
  BiShengIRSCFTransformOps
  BiShengIRSCFTransforms
  BiShengIRSCFUtils
  BiShengIRScopeDialect
  BiShengIRScopeTransforms
  BiShengIRSymbolDialect
  BiShengIRTensorDialect
  BiShengIRTensorTransforms
  BiShengIRToLLVMIRTranslationRegistration
  BiShengIRToolUtils
  BiShengIRTransform
  BiShengIRTransformOps
  BiShengIRTritonExtIR
  BiShengIRTritonExtension
  BiShengIRTritonTransforms
  BiShengIRVersionLib
  BishengIRLLVMTransforms
  MLIRAVEDialect
  MLIRArithToHIVMLLVM
  MLIRHACCToLLVM
  MLIRHACCToLLVMIRTranslation
  MLIRHIVMRegbaseIntrinsDialect
  MLIRHIVMRegbaseIntrinsToLLVMIRTranslation
  MLIRHIVMRegbaseIntrinsUtils
  MLIRHIVMToLLVM
  MLIRHIVMToLLVMIRTranslation
  MLIRTestTransforms
  GluonIR
  MLIRFuncAllExtensions
  TritonInstrumentTransforms
  TritonLLVMIR
  NVHopperTransforms
  GluonTransforms
  TritonTestAnalysis
  TritonTestDialect
)

add_bishengir_publish_tool(hivmc
  hivmc.cpp

  DEPENDS
  ${LIBS}
)

target_include_directories(hivmc PRIVATE ${CMAKE_CURRENT_SOURCE_DIR}/include)
target_link_libraries(hivmc PRIVATE ${LIBS})
mlir_check_all_link_libraries(hivmc)
