//===-- HIVMAttrs.td - Entry point for bindings -----*- tablegen -*-===//
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//

#ifndef PYTHON_BINDINGS_HIVM_ATTRDEFS_TD
#define PYTHON_BINDINGS_HIVM_ATTRDEFS_TD

include "bishengir/Dialect/HIVM/IR/HIVMAttrs.td"

#endif // PYTHON_BINDINGS_HIVM_ATTRDEFS_TD
