//===- InitAllPasses.h - MLIR Passes Registration ---------------*- C++ -*-===//
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//
//
// This file defines a helper to trigger the registration of all dialects and
// passes to the system.
//
//===----------------------------------------------------------------------===//

#ifndef BISHENGIR_INITALLPASSES_H
#define BISHENGIR_INITALLPASSES_H

#include "bishengir/Config/bishengir-config.h"
#include "bishengir/Conversion/Passes.h"
#include "bishengir/Dialect/Analysis/VFFusion/Passes.h"
#include "bishengir/Dialect/Annotation/Transforms/Passes.h"
#include "bishengir/Dialect/Arith/Transforms/Passes.h"
#include "bishengir/Dialect/HACC/Transforms/Passes.h"
#include "bishengir/Dialect/HFusion/Pipelines/Passes.h"
#include "bishengir/Dialect/HFusion/Transforms/Passes.h"
#include "bishengir/Dialect/HIVM/Pipelines/Passes.h"
#include "bishengir/Dialect/HIVM/Transforms/Passes.h"
#include "bishengir/Dialect/MemRef/Transforms/Passes.h"
#include "bishengir/Dialect/Mesh/Transforms/Passes.h"
#include "bishengir/Dialect/SCF/Transforms/Passes.h"
#include "bishengir/Dialect/Scope/Transforms/Passes.h"
#include "bishengir/Dialect/Symbol/Transforms/Passes.h"
#include "bishengir/Dialect/Tensor/Transforms/Passes.h"
#include "bishengir/Dialect/Triton/Pipelines/Passes.h"
#include "bishengir/Dialect/Triton/Transforms/Passes.h"
#include "bishengir/Dialect/Vector/Transforms/Passes.h"
#include "bishengir/Tools/bishengir-compile/PassPipeline.h"
#include "bishengir/Tools/bishengir-hivm-compile/PassPipeline.h"
#include "bishengir/Transforms/Passes.h"

#ifdef BISHENGIR_ENABLE_EXECUTION_ENGINE
#include "bishengir/ExecutionEngine/Passes.h"
#endif

#if BISHENGIR_ENABLE_TORCH_CONVERSIONS
#include "bishengir/Dialect/Torch/Pipelines/Passes.h"
#include "bishengir/Dialect/Torch/Transforms/Passes.h"
#include "torch-mlir-dialects/Dialect/TMTensor/Transforms/Passes.h"
#include "torch-mlir/Conversion/Passes.h"
#include "torch-mlir/Conversion/TorchOnnxToTorch/Passes.h"
#include "torch-mlir/Dialect/Torch/Transforms/Passes.h"
#include "torch-mlir/Dialect/TorchConversion/Transforms/Passes.h"
#endif

namespace bishengir {

// This function may be called to register the bishengir-specific MLIR passes
// with the global registry.
inline void registerAllPasses() {
  // Conversion passes
  bishengir::registerConversionPasses();

  // Dialect passes
  mlir::analysis::registerAnalysisPasses();
  mlir::annotation::registerAnnotationPasses();
  mlir::arith::registerBishengIRArithPasses();
  mlir::hfusion::registerHFusionPasses();
  mlir::hivm::registerHIVMPasses();
  mlir::memref::registerBishengIRMemRefPasses();
  mlir::mesh::registerBishengIRMeshPasses();
  mlir::tensor::registerBishengIRTensorPasses();
  mlir::scf::registerBishengIRSCFPasses();
  mlir::vector::registerBishengIRVectorPasses();
  mlir::hacc::registerHACCPasses();
  mlir::scope::registerScopePasses();
  mlir::symbol::registerSymbolPasses();

  // Transforms passes
  bishengir::registerBishengIRTransformPasses();

#if BISHENGIR_ENABLE_TORCH_CONVERSIONS
  bishengir::registerConvertTorchToHFusion();
  mlir::torch::registerLiteralDataTypeCast();
  mlir::torch::registerTorchPasses();
  mlir::torch::registerTorchConversionPasses();
  mlir::torch::registerConversionPasses();
  mlir::torch::onnx_c::registerTorchOnnxToTorchPasses();
  mlir::torch::TMTensor::registerPasses();
#endif

  // Dialect passes that aren't generated by tblgen
  mlir::hfusion::registerAutoScheduleInterpreterPass();
  mlir::hfusion::registerEraseAutoSchedulePass();

  // Dialect pipelines
  bishengir::registerBiShengIRCompilePass();
  bishengir::registerBiShengIRHIVMCompilePass();
  mlir::hivm::registerLowerHIVMPipelines();
  mlir::hivm::registerConvertToHIVMPipelines();
  mlir::hfusion::registerLowerHFusionPipelines();

#ifdef BISHENGIR_ENABLE_EXECUTION_ENGINE
  mlir::execution_engine::registerExecutionEnginePasses();
  mlir::execution_engine::registerAllPipelines();
#endif

#if BISHENGIR_ENABLE_TORCH_CONVERSIONS
  bishengir::registerTorchToHFusionPipelines();
#endif

  bishengir::triton::registerBiShengIRTritonPasses();
  bishengir::triton::registerLowerTritonPipeline();

}

} // namespace bishengir

#endif // BISHENGIR_INITALLPASSES_H
