//===- embed-bc-to-cpp.cpp - embed-bc-to-cpp tool----------------*- C++ -*-===//
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//
//
// A tool used to embed meta ops bitcode files into cpp libraries.
//
//===----------------------------------------------------------------------===//

#include "mlir/Support/FileUtilities.h"
#include "llvm/Support/MemoryBuffer.h"
#include "llvm/Support/Path.h"
#include "llvm/Support/ToolOutputFile.h"

#include <iomanip>
#include <iostream>
#include <sstream>
#include <string>
#include <vector>

using namespace std;
using namespace llvm;
using namespace mlir;

#ifndef NDEBUG
const int32_t MAX_BC_SIZE = 33554432; // 1<<25 - 32MB
#endif

bool readBinaryFile(const string &fileName, vector<unsigned char> &buffer) {
  string errorMessage;
  auto input = openInputFile(fileName, &errorMessage);
  if (!input) {
    cerr << errorMessage << endl;
    return false;
  }

  const char *data = input->getBufferStart();
  size_t size = input->getBufferSize();
  assert(size < MAX_BC_SIZE &&
         "the size of the .bc file is larger that expected.");
  buffer.resize(size);
  copy(data, data + size, buffer.begin());
  return true;
}

void writeWarningHeader(raw_ostream &os) {
  os << "/**********************************************\n"
     << "* !!!!! WARNING: AUTO-GENERATED FILE !!!!!    *\n"
     << "* This file was generated by embed-bc-to-cpp. *\n"
     << "* Manual edits will be lost on regeneration.  *\n"
     << "**********************************************/\n\n";
}

void writeHeaderFile(raw_ostream &os, StringRef fileName, const string &arrName,
                     const string &sizeVar) {
  writeWarningHeader(os);
  string headerDef = fileName.upper() + "_H";

  os << "#ifndef " << headerDef << "\n";
  os << "#define " << headerDef << "\n\n";
  os << "#include <cstdint>\n\n";
  os << "extern const int32_t " << sizeVar << ";\n";
  os << "extern const unsigned char " << arrName << "[];\n";
  os << "\n#ifdef __cplusplus\n";
  os << "extern \"C\" {\n";
  os << "#endif\n\n";
  os << "  int32_t get_" << arrName << "_size();\n";
  os << "  const unsigned char* get_" << arrName << "_data();\n";
  os << "\n#ifdef __cplusplus\n";
  os << "}\n";
  os << "#endif\n";
  os << "\n#endif\n";
}

void writeSourceFile(raw_ostream &os, const vector<unsigned char> &data,
                     const string &outputFilenameH, const string &arrName,
                     const string &sizeVar) {
  writeWarningHeader(os);
  os << "#include \"" << outputFilenameH << "\"\n\n";
  os << "const int32_t " << sizeVar << " = " << data.size() << ";\n\n";
  os << "const unsigned char " << arrName << "[" << sizeVar << "] = {\n";

  const int bytesPerLine = 32;
  for (size_t i = 0; i < data.size(); ++i) {
    if (i % bytesPerLine == 0) {
      if (i != 0)
        os << "\n";
      os << "    ";
    }
    stringstream dataHex;
    dataHex << "0x" << hex << setw(2) /*2 characters reserved*/ << setfill('0')

            << static_cast<int>(data[i]);
    os << dataHex.str();
    if (i + 1 != data.size())
      os << ", ";
  }

  os << "\n};\n";
  os << "\n#ifdef __cplusplus\n";
  os << "extern \"C\" {\n";
  os << "#endif\n\n";
  os << "  int32_t get_" << arrName << "_size() { return " << sizeVar
     << "; }\n";
  os << "  const unsigned char* get_" << arrName << "_data() { return "
     << arrName << "; }\n";
  os << "\n#ifdef __cplusplus\n";
  os << "}\n";
  os << "#endif\n";
}

bool writeByteArrayToCpp(const string &outputFileDir,
                         const vector<unsigned char> &data) {
  string outputFileDirH = outputFileDir + ".h";
  string outputFileDirCPP = outputFileDir + ".cpp";
  auto outFileH = openOutputFile(outputFileDirH);
  if (!outFileH) {
    cerr << "Failed to create output file: " << outputFileDirH << endl;
    return false;
  }

  auto outFileCPP = openOutputFile(outputFileDirCPP);
  if (!outFileCPP) {
    cerr << "Failed to create output file: " << outputFileDirCPP << endl;
    return false;
  }

  outFileH->keep();
  outFileCPP->keep();

  auto fileName = sys::path::filename(outputFileDir);
  string arrName = fileName.str();
  string headerDef = fileName.upper() + "_H";
  string sizeVar = "SIZE_OF_" + fileName.upper();

  writeHeaderFile(outFileH->os(), fileName, arrName, sizeVar);
  writeSourceFile(outFileCPP->os(), data, outputFileDirH, arrName, sizeVar);

  return true;
}

int main(int argc, char **argv) {
  if (argc != 3 /* must have 3 arguments */) {
    cerr << "Usage: " << argv[0] << " <input_file> <output_cpp_file>" << endl;
    return EXIT_FAILURE;
  }

  string inputFile = argv[1];
  string outputFile = argv[2];
  vector<unsigned char> binaryData;

  if (!readBinaryFile(inputFile, binaryData) ||
      !writeByteArrayToCpp(outputFile, binaryData)) {
    cerr << "Failed: " << inputFile << endl;
    return EXIT_FAILURE;
  }

  return EXIT_SUCCESS;
}
