//===- ConvertSharedPtrToMemDesc.cpp - ptr<6> to memdesc conversion ------===//
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//
//
// This pass runs immediately after ConvertTritonToTritonGPU.  It finds
// tt.load / tt.store operations whose pointer tensors have address-space 6
// (shared memory / UB) and rewrites them to ttg.local_load / ttg.local_store
// with ttg.memdesc types.
//
// The typical input pattern (generated by HIVMToTriton for shared-memory
// accesses) is:
//
//   %splat  = tt.splat  %arg : !tt.ptr<f32, 6> -> tensor<Nx!tt.ptr<f32, 6>>
//   %addptr = tt.addptr %splat, %offsets : ...
//   tt.store %addptr, %data : tensor<Nx!tt.ptr<f32, 6>, #blocked>
//
// After this pass the IR becomes:
//
//   // %arg type changed:  !tt.ptr<f32, 6>  -->  !ttg.memdesc<Nxf32, #shared>
//   ttg.local_store %data, %arg : tensor<Nxf32, #blocked>
//                                  -> !ttg.memdesc<Nxf32, #shared, #smem>
//
//===----------------------------------------------------------------------===//

#include "mlir/IR/Builders.h"
#include "mlir/IR/BuiltinOps.h"
#include "bishengir/Dialect/TritonExt/IR/TritonExtAttrs.h"
#include "triton/Dialect/Triton/IR/Dialect.h"
#include "triton/Dialect/Triton/IR/Types.h"
#include "triton/Dialect/TritonGPU/IR/Dialect.h"

#define GEN_PASS_DEF_CONVERTSHAREDPTRTOMEMDESC
#include "bishengir/Dialect/Triton/Transforms/Passes.h"
#include "bishengir/Dialect/Triton/Transforms/Passes.h.inc"

using namespace mlir;
using namespace mlir::triton;

namespace {

/// Return true when \p ty is `!tt.ptr<..., 6>`.
static bool isSharedPtr(Type ty) {
  auto ptrTy = dyn_cast<triton::PointerType>(ty);
  return ptrTy && ptrTy.getAddressSpace() == 6;
}

/// Return true when \p ty is `tensor<...x!tt.ptr<..., 6>, ...>`.
static bool isSharedPtrTensor(Type ty) {
  auto tensorTy = dyn_cast<RankedTensorType>(ty);
  return tensorTy && isSharedPtr(tensorTy.getElementType());
}

/// Walk backwards through AddPtrOp / SplatOp to reach the scalar base pointer.
static Value traceToBasePtr(Value ptrTensor) {
  while (true) {
    if (auto addptr = ptrTensor.getDefiningOp<triton::AddPtrOp>()) {
      ptrTensor = addptr.getPtr();
      continue;
    }
    if (auto splat = ptrTensor.getDefiningOp<triton::SplatOp>()) {
      return splat.getSrc();
    }
    return ptrTensor;
  }
}

/// Collect the chain of ops (AddPtrOp, SplatOp) between a load/store's pointer
/// operand and the scalar base pointer, so we can DCE them after rewriting.
static void collectPtrChain(Value ptrTensor,
                            SmallVectorImpl<Operation *> &chain) {
  while (true) {
    if (auto addptr = ptrTensor.getDefiningOp<triton::AddPtrOp>()) {
      chain.push_back(addptr);
      ptrTensor = addptr.getPtr();
      continue;
    }
    if (auto splat = ptrTensor.getDefiningOp<triton::SplatOp>()) {
      chain.push_back(splat);
      return;
    }
    return;
  }
}

/// Build a MemDescType for the given tensor shape / element type.
/// If \p fractalAttr is non-null, use FractalSharedEncodingAttr; otherwise
/// fall back to an unswizzled SwizzledSharedEncodingAttr.
static triton::gpu::MemDescType
buildMemDescType(MLIRContext *ctx, ArrayRef<int64_t> shape, Type elemType,
                 Attribute fractalAttr = nullptr) {
  auto smem = triton::gpu::SharedMemorySpaceAttr::get(ctx);

  // Build a trivial CTA layout.
  unsigned rank = shape.size();
  SmallVector<unsigned> order;
  for (int i = rank - 1; i >= 0; --i)
    order.push_back(static_cast<unsigned>(i));

  SmallVector<unsigned> ones(rank, 1u);
  auto ctaLayout =
      triton::gpu::CTALayoutAttr::get(ctx, ones, ones, order);

  Attribute encoding;
  if (auto strAttr = dyn_cast_or_null<StringAttr>(fractalAttr)) {
    // Parse "zN" / "nZ" string to FractalLayoutType enum.
    auto layoutType =
        bishengir::triton_ext::symbolizeFractalLayoutType(strAttr.getValue());
    assert(layoutType && "invalid hivm.fractal_layout value");
    encoding = bishengir::triton_ext::FractalSharedEncodingAttr::get(
        ctx, /*fractalM0=*/16, /*fractalN0=*/16, *layoutType, ctaLayout);
  } else {
    encoding = triton::gpu::SwizzledSharedEncodingAttr::get(
        ctx, /*vec=*/1, /*perPhase=*/1, /*maxPhase=*/1, order, ctaLayout);
  }

  return triton::gpu::MemDescType::get(shape, elemType, encoding, smem,
                                       /*mutableMemory=*/true);
}

/// Information gathered for a single shared-memory base pointer.
struct BasePtrInfo {
  unsigned argIndex = 0;
  SmallVector<int64_t> shape;
  Type elemType;
  /// Optional fractal layout attribute ("zN" or "nZ") from hivm.fractal_layout.
  Attribute fractalAttr;
  SmallVector<triton::LoadOp> loads;
  SmallVector<triton::StoreOp> stores;
  /// Chains of AddPtrOp / SplatOp to DCE after rewriting.
  SmallVector<Operation *> deadOps;
};

struct ConvertSharedPtrToMemDescPass
    : public bishengir::impl::ConvertSharedPtrToMemDescBase<
          ConvertSharedPtrToMemDescPass> {

  void runOnOperation() override {
    getOperation().walk([&](triton::FuncOp func) {
      if (failed(convertFunction(func)))
        signalPassFailure();
    });
  }

private:
  LogicalResult convertFunction(triton::FuncOp func) {
    MLIRContext *ctx = func.getContext();

    // --- Step 1: Gather all shared-memory load/store ops ----------------
    DenseMap<Value, BasePtrInfo> baseMap;

    auto processOp = [&](Operation *op, Value ptrTensor, ArrayRef<int64_t> shape,
                         Type elemType) {
      if (!isSharedPtrTensor(ptrTensor.getType()))
        return;

      Value basePtr = traceToBasePtr(ptrTensor);
      auto blockArg = dyn_cast<BlockArgument>(basePtr);
      if (!blockArg)
        return;

      auto &info = baseMap[basePtr];
      info.argIndex = blockArg.getArgNumber();
      info.shape.assign(shape.begin(), shape.end());
      info.elemType = elemType;
      // Check for fractal layout attribute on the function argument.
      if (!info.fractalAttr)
        info.fractalAttr = func.getArgAttr(info.argIndex, "hivm.fractal_layout");

      if (auto store = dyn_cast<triton::StoreOp>(op))
        info.stores.push_back(store);
      else if (auto load = dyn_cast<triton::LoadOp>(op))
        info.loads.push_back(load);

      collectPtrChain(ptrTensor, info.deadOps);
    };

    func.walk([&](triton::StoreOp store) {
      auto dataTy = dyn_cast<RankedTensorType>(store.getValue().getType());
      if (!dataTy)
        return;
      processOp(store, store.getPtr(), dataTy.getShape(),
                dataTy.getElementType());
    });

    func.walk([&](triton::LoadOp load) {
      auto resTy = dyn_cast<RankedTensorType>(load.getResult().getType());
      if (!resTy)
        return;
      processOp(load, load.getPtr(), resTy.getShape(),
                resTy.getElementType());
    });

    if (baseMap.empty())
      return success();

    // --- Step 2: Rewrite each base-pointer group ------------------------
    OpBuilder builder(ctx);

    for (auto &[basePtr, info] : baseMap) {
      auto memDescTy = buildMemDescType(ctx, info.shape, info.elemType,
                                        info.fractalAttr);
      auto blockArg = cast<BlockArgument>(basePtr);

      // Change block argument type  ptr<6> --> memdesc.
      blockArg.setType(memDescTy);

      // Rewrite stores: tt.store %ptrs, %data  -->  ttg.local_store %data, %md
      for (auto store : info.stores) {
        builder.setInsertionPoint(store);
        builder.create<triton::gpu::LocalStoreOp>(store.getLoc(),
                                                  store.getValue(), blockArg);
        store.erase();
      }

      // Rewrite loads: %v = tt.load %ptrs  -->  %v = ttg.local_load %md
      for (auto load : info.loads) {
        builder.setInsertionPoint(load);
        auto localLoad = builder.create<triton::gpu::LocalLoadOp>(
            load.getLoc(), load.getResult().getType(), blockArg);
        load.getResult().replaceAllUsesWith(localLoad.getResult());
        load.erase();
      }

      // DCE the splat / addptr chains (erase in reverse so uses are gone).
      for (auto *op : info.deadOps) {
        if (op->use_empty())
          op->erase();
      }
    }

    // --- Step 3: Update function type signature -------------------------
    SmallVector<Type> newArgTypes;
    for (auto arg : func.getArguments())
      newArgTypes.push_back(arg.getType());
    auto oldFuncTy = func.getFunctionType();
    func.setFunctionType(
        FunctionType::get(ctx, newArgTypes, oldFuncTy.getResults()));

    return success();
  }
};

} // namespace

namespace bishengir {
namespace triton {

std::unique_ptr<mlir::Pass> createConvertSharedPtrToMemDescPass() {
  return std::make_unique<ConvertSharedPtrToMemDescPass>();
}

} // namespace triton
} // namespace bishengir
